// Datos de los reactivos
const reactivos = {
    // Reactivos orgánicos
    "àcid tioglicòlic": { numero: "540", estado: "líquid", tipo: "orgánico" },
    "murexida": { numero: "605", estado: "sòlid", tipo: "orgánico" },
    "metilisobutilcetona": { numero: "501", estado: "líquid", tipo: "orgánico" },
    "1-dodecanol": { numero: "502", estado: "líquid", tipo: "orgánico" },
    "n-pentà": { numero: "503", estado: "líquid", tipo: "orgánico" },
    "formaldehid 35-40%": { numero: "504", estado: "líquid", tipo: "orgánico" },
    "alcohol etílic (etanol absolut)": { numero: "505", estado: "líquid", tipo: "orgánico" },
    "eter dietílic (dietileter)": { numero: "509", estado: "líquid", tipo: "orgánico" },
    "acetat de n-butil": { numero: "510", estado: "líquid", tipo: "orgánico" },
    "acetona": { numero: "554", estado: "líquid", tipo: "orgánico" },
    "alcohol benzílic": { numero: "511", estado: "líquid", tipo: "orgánico" },
    "alcohol propílic (1-propanol o n-propanol)": { numero: "516", estado: "líquid", tipo: "orgánico" },
    "acetat d'etil": { numero: "520", estado: "líquid", tipo: "orgánico" },
    "benzè": { numero: "522", estado: "líquid", tipo: "orgánico" },
    "alcohol isopropílic (isopropanol, 2-propanol)": { numero: "524", estado: "líquid", tipo: "orgánico" },
    "nitrobenzè": { numero: "529", estado: "líquid", tipo: "orgánico" },
    "tetraclorur de carboni": { numero: "539", estado: "líquid", tipo: "orgánico" },
    "piridina": { numero: "547", estado: "líquid", tipo: "orgánico" },
    "trietanolamina 98%": { numero: "553", estado: "líquid", tipo: "orgánico" },
    "alcohol terc-butílic (terc-butanol)": { numero: "558", estado: "líquid", tipo: "orgánico" },
    "tetrahidrofuran": { numero: "561", estado: "líquid", tipo: "orgánico" },
    "isohexà": { numero: "562b", estado: "líquid", tipo: "orgánico" },
    "n-hexà": { numero: "562", estado: "líquid", tipo: "orgánico" },
    "alcohol n-butílic (n-butanol o 1-butanol)": { numero: "564", estado: "líquid", tipo: "orgánico" },
    "butanona": { numero: "567", estado: "líquid", tipo: "orgánico" },
    "fenol": { numero: "569", estado: "líquid", tipo: "orgánico" },
    "fenol sòlid": { numero: "569b", estado: "sòlid", tipo: "orgánico" },
    "etilenglicol": { numero: "571", estado: "líquid", tipo: "orgánico" },
    "alcohol 2 butílic (2-butanol)": { numero: "573", estado: "líquid", tipo: "orgánico" },
    "metiletilcetona": { numero: "574", estado: "líquid", tipo: "orgánico" },
    "iso-octà": { numero: "575", estado: "líquid", tipo: "orgánico" },
    "2,2-dimetoxipropà": { numero: "576", estado: "líquid", tipo: "orgánico" },
    "acetat de metil": { numero: "580", estado: "líquid", tipo: "orgánico" },
    "toluè": { numero: "582", estado: "líquid", tipo: "orgánico" },
    "acetonitril": { numero: "583", estado: "líquid", tipo: "orgánico" },
    "xilè": { numero: "588", estado: "líquid", tipo: "orgánico" },
    "alcohol iso-amílic (3-metil-1-butanol)": { numero: "589", estado: "líquid", tipo: "orgánico" },
    "diclorometà": { numero: "594", estado: "líquid", tipo: "orgánico" },
    "n-heptà": { numero: "598", estado: "líquid", tipo: "orgánico" },
    "eter de petróli 40-60ºc": { numero: "603", estado: "líquid", tipo: "orgánico" },
    "dietilenglycol-monobutilèter": { numero: "604", estado: "líquid", tipo: "orgánico" },
    "alcohol isobutílic (isobutanol)": { numero: "610", estado: "líquid", tipo: "orgánico" },
    "anhídrid acètic": { numero: "612", estado: "líquid", tipo: "orgánico" },
    "anilina": { numero: "614", estado: "líquid", tipo: "orgánico" },
    "ciclohexà": { numero: "621", estado: "líquid", tipo: "orgánico" },
    "2-pentanol": { numero: "624", estado: "líquid", tipo: "orgánico" },
    "tricloroform (cloroform)": { numero: "625", estado: "líquid", tipo: "orgánico" },
    "acetat d'isobutil": { numero: "641", estado: "líquid", tipo: "orgánico" },
    "1,2-dicloroetano": { numero: "645", estado: "líquid", tipo: "orgánico" },
    "difenilamina": { numero: "647", estado: "líquid", tipo: "orgánico" },
    "di-iso-butilcetona": { numero: "656", estado: "líquid", tipo: "orgánico" },
    "àcid fòrmic": { numero: "657", estado: "líquid", tipo: "orgánico" },
    "metadien-(1,3)": { numero: "668", estado: "líquid", tipo: "orgánico" },
    "propilacetat": { numero: "670", estado: "líquid", tipo: "orgánico" },
    "eter isopropílico": { numero: "672", estado: "líquid", tipo: "orgánico" },
    "propanal, propioaldehid": { numero: "675", estado: "líquid", tipo: "orgánico" },
    "n,n-dimetilformamida": { numero: "696", estado: "líquid", tipo: "orgánico" },
    "tert-butil metil eter": { numero: "697", estado: "líquid", tipo: "orgánico" },
    "anisaldehid/acit acètic glacial/metanol/sulfúric àcid": { numero: "704", estado: "líquid", tipo: "orgánico" },
    "aquagent titrant 5": { numero: "709", estado: "líquid", tipo: "orgánico" },
    "1-pentanol": { numero: "711", estado: "líquid", tipo: "orgánico" },
    "éter monofenílico del etilenglicol": { numero: "713", estado: "líquid", tipo: "orgánico" },
    "dimetilsulfóxido": { numero: "717", estado: "líquid", tipo: "orgánico" },
    "1-octanol": { numero: "720", estado: "líquid", tipo: "orgánico" },
    "ethyl trans-3-hexenoate": { numero: "721", estado: "líquid", tipo: "orgánico" },
    "acetat de benzil": { numero: "724", estado: "líquid", tipo: "orgánico" },
    "tetracloroetilè": { numero: "725", estado: "líquid", tipo: "orgánico" },
    "dioxà": { numero: "726", estado: "líquid", tipo: "orgánico" },
    "alcohol amílic": { numero: "735", estado: "líquid", tipo: "orgánico" },
    "àcid benzaldehid": { numero: "517", estado: "líquid", tipo: "orgánico" },
    "alcohol metílic (metanol)": { numero: "570", estado: "líquid", tipo: "orgánico" },
    "formamida": { numero: "719", estado: "líquid", tipo: "orgánico" },
    "àcid oxàlic 2-h2o": { numero: "579b", estado: "sòlid", tipo: "orgánico" },
    "àcid acetilsalicílic": { numero: "626", estado: "sòlid", tipo: "orgánico" },
    "brucina": { numero: "633", estado: "sòlid", tipo: "orgánico" },
    "àcid malèic": { numero: "677", estado: "sòlid", tipo: "orgánico" },
    "àcid 4-aminobenzoic": { numero: "500", estado: "sòlid", tipo: "orgánico" },
    "àcid salicílic": { numero: "506", estado: "sòlid", tipo: "orgánico" },
    "àcid d l-màlic": { numero: "507", estado: "sòlid", tipo: "orgánico" },
    "àcid succínic": { numero: "508", estado: "sòlid", tipo: "orgánico" },
    "àcid 5-sulfosalicílic": { numero: "512", estado: "sòlid", tipo: "orgánico" },
    "àcid 5-sulfosalicílic 2h2o": { numero: "512b", estado: "sòlid", tipo: "orgánico" },
    "àcido sulfanílic": { numero: "513", estado: "sòlid", tipo: "orgánico" },
    "àcido esteàric": { numero: "514", estado: "sòlid", tipo: "orgánico" },
    "bromoform": { numero: "515", estado: "líquid", tipo: "orgánico" },
    "àcid cinàmic": { numero: "518", estado: "sòlid", tipo: "orgánico" },
    "glucosa anhidra": { numero: "519", estado: "sòlid", tipo: "orgánico" },
    "àcido l-(+)tartàric": { numero: "521", estado: "sòlid", tipo: "orgánico" },
    "anhídrid ftàlic": { numero: "523", estado: "sòlid", tipo: "orgánico" },
    "l-arginina": { numero: "525", estado: "sòlid", tipo: "orgánico" },
    "xilosa": { numero: "526", estado: "sòlid", tipo: "orgánico" },
    "l-prolina": { numero: "527", estado: "sòlid", tipo: "orgánico" },
    "resorcina": { numero: "530", estado: "sòlid", tipo: "orgánico" },
    "àcid benzoic": { numero: "531", estado: "sòlid", tipo: "orgánico" },
    "hidracina hidróxid": { numero: "533", estado: "líquid", tipo: "orgánico" },
    "l-alanina": { numero: "534", estado: "sòlid", tipo: "orgánico" },
    "ninhidrina": { numero: "535", estado: "sòlid", tipo: "orgánico" },
    "hidrazobenzol": { numero: "536", estado: "sòlid", tipo: "orgánico" },
    "àcid l-(+)ascòrbic": { numero: "537", estado: "sòlid", tipo: "orgánico" },
    "hidroquinona": { numero: "538", estado: "sòlid", tipo: "orgánico" },
    "o-toluidina": { numero: "541", estado: "líquid", tipo: "orgánico" },
    "o-toluidina 0,1%": { numero: "541c", estado: "líquid", tipo: "orgánico" },
    "àcido tricloroacètic": { numero: "542", estado: "sòlid", tipo: "orgánico" },
    "glicerina": { numero: "543", estado: "líquid", tipo: "orgánico" },
    "d-manita": { numero: "544", estado: "sòlid", tipo: "orgánico" },
    "metilglicol": { numero: "545", estado: "líquid", tipo: "orgánico" },
    "clorhidrat d'anilina": { numero: "546", estado: "sòlid", tipo: "orgánico" },
    "gelatina": { numero: "548", estado: "sòlid", tipo: "orgánico" },
    "tartracina": { numero: "549", estado: "sòlid", tipo: "orgánico" },
    "azorubina lz doble": { numero: "550", estado: "sòlid", tipo: "orgánico" },
    "amarillo quinolina": { numero: "551", estado: "sòlid", tipo: "orgánico" },
    "ninhidrina en 2-propanol": { numero: "552", estado: "líquid", tipo: "orgánico" },
    "àcid pirrolidinditiocarboxílic": { numero: "555", estado: "sòlid", tipo: "orgánico" },
    "eritrosina": { numero: "556", estado: "sòlid", tipo: "orgánico" },
    "nitrofenilhidracina": { numero: "557", estado: "sòlid", tipo: "orgánico" },
    "1,10-fenantrolina 1h2o": { numero: "559", estado: "sòlid", tipo: "orgánico" },
    "hexametilenotetramina": { numero: "560", estado: "sòlid", tipo: "orgánico" },
    "sacarosa": { numero: "563", estado: "sòlid", tipo: "orgánico" },
    "tris (hidroximetil) aminometà": { numero: "565", estado: "sòlid", tipo: "orgánico" },
    "quinoleína": { numero: "566", estado: "líquid", tipo: "orgánico" },
    "acetofenona": { numero: "568", estado: "líquid", tipo: "orgánico" },
    "metilsalicilat": { numero: "572", estado: "líquid", tipo: "orgánico" },
    "l-lisina monohidroclorur": { numero: "577", estado: "sòlid", tipo: "orgánico" },
    "hexametilenodiamina": { numero: "578", estado: "sòlid", tipo: "orgánico" },
    "àcid oxàlic anhidre": { numero: "579", estado: "sòlid", tipo: "orgánico" },
    "l-cistina": { numero: "581", estado: "sòlid", tipo: "orgánico" },
    "clorur d'adipoil": { numero: "584", estado: "líquid", tipo: "orgánico" },
    "naftalè": { numero: "585", estado: "sòlid", tipo: "orgánico" },
    "antracè": { numero: "586", estado: "sòlid", tipo: "orgánico" },
    "urea": { numero: "587", estado: "sòlid", tipo: "orgánico" },
    "goma aràbiga": { numero: "590", estado: "sòlid", tipo: "orgánico" },
    "hidroxiquinoleina (oxina)": { numero: "591", estado: "sòlid", tipo: "orgánico" },
    "fenolftaleina": { numero: "592", estado: "sòlid", tipo: "orgánico" },
    "negre d'eriocrom t (net)": { numero: "593", estado: "sòlid", tipo: "orgánico" },
    "dimetilglioxima": { numero: "595", estado: "sòlid", tipo: "orgánico" },
    "cafeína": { numero: "596", estado: "sòlid", tipo: "orgánico" },
    "tiourea": { numero: "597", estado: "sòlid", tipo: "orgánico" },
    "quinina hidroxi...": { numero: "599", estado: "sòlid", tipo: "orgánico" },
    "quinina hidroxi... 2h2o": { numero: "599b", estado: "sòlid", tipo: "orgánico" },
    "agar": { numero: "600", estado: "sòlid", tipo: "orgánico" },
    "1,5-difenilcarbazida": { numero: "601", estado: "sòlid", tipo: "orgánico" },
    "hidroxilamina clorur": { numero: "602", estado: "sòlid", tipo: "orgánico" },
    "morfolina": { numero: "606", estado: "líquid", tipo: "orgánico" },
    "àcid l-glutàmic": { numero: "607", estado: "sòlid", tipo: "orgánico" },
    "bencidina": { numero: "608", estado: "sòlid", tipo: "orgánico" },
    "d(-)fructosa": { numero: "609", estado: "sòlid", tipo: "orgánico" },
    "ditizona": { numero: "611", estado: "sòlid", tipo: "orgánico" },
    "acetanilida": { numero: "613", estado: "sòlid", tipo: "orgánico" },
    "àcid gàlic": { numero: "615b", estado: "sòlid", tipo: "orgánico" },
    "àcid pirogalic": { numero: "615", estado: "sòlid", tipo: "orgánico" },
    "midó": { numero: "616", estado: "sòlid", tipo: "orgánico" },
    "àcid cítric": { numero: "617", estado: "sòlid", tipo: "orgánico" },
    "àcid cítric 1h2o": { numero: "617b", estado: "sòlid", tipo: "orgánico" },
    "àcid ftàlic": { numero: "618", estado: "sòlid", tipo: "orgánico" },
    "cloramina t": { numero: "619", estado: "sòlid", tipo: "orgánico" },
    "cloramina t 3h2o": { numero: "619b", estado: "sòlid", tipo: "orgánico" },
    "anhídrid màlic": { numero: "620", estado: "sòlid", tipo: "orgánico" },
    "èter de petroli 60-80ºc": { numero: "622", estado: "líquid", tipo: "orgánico" },
    "4-dimetilaminobenzaldehid": { numero: "623", estado: "sòlid", tipo: "orgánico" },
    "n,n-dimetilanilina": { numero: "627", estado: "líquid", tipo: "orgánico" },
    "tioacetamida": { numero: "629", estado: "sòlid", tipo: "orgánico" },
    "dietanolamina": { numero: "631", estado: "líquid", tipo: "orgánico" },
    "1,2-propilenglicol": { numero: "632", estado: "líquid", tipo: "orgánico" },
    "n-aliltiourea": { numero: "634", estado: "sòlid", tipo: "orgánico" },
    "àcid metanosulfónic": { numero: "635", estado: "líquid", tipo: "orgánico" },
    "naftilamoni clorur": { numero: "636", estado: "sòlid", tipo: "orgánico" },
    "tributilmetil amoni clorur": { numero: "637", estado: "líquid", tipo: "orgánico" },
    "metiltioacetil amoni bromur": { numero: "638", estado: "sòlid", tipo: "orgánico" },
    "benciltrietil amoni clorur": { numero: "639", estado: "sòlid", tipo: "orgánico" },
    "àcid a-bromoisobutíric": { numero: "640", estado: "sòlid", tipo: "orgánico" },
    "sulfanilamida": { numero: "642", estado: "sòlid", tipo: "orgánico" },
    "n-(1-naftil) etilendiamina diclorhidrat": { numero: "643", estado: "sòlid", tipo: "orgánico" },
    "n-n-dimetil-p fenilendiamin oxalat": { numero: "644", estado: "sòlid", tipo: "orgánico" },
    "acetoacetato de etilo": { numero: "646", estado: "líquid", tipo: "orgánico" },
    "àcid barbitúric": { numero: "648", estado: "sòlid", tipo: "orgánico" },
    "paraformaldehido": { numero: "649", estado: "sòlid", tipo: "orgánico" },
    "2,6-dicloroindofenol": { numero: "650", estado: "sòlid", tipo: "orgánico" },
    "acetil clorur": { numero: "651", estado: "líquid", tipo: "orgánico" },
    "hidracina sulfat": { numero: "652", estado: "sòlid", tipo: "orgánico" },
    "hyamina 1622": { numero: "653", estado: "sòlid", tipo: "orgánico" },
    "torina 8-hidrato pa": { numero: "654", estado: "sòlid", tipo: "orgánico" },
    "àcid pirogàlic": { numero: "655", estado: "sòlid", tipo: "orgánico" },
    "2-furfuraldehido": { numero: "658", estado: "líquid", tipo: "orgánico" },
    "àcid oleic": { numero: "659", estado: "líquid", tipo: "orgánico" },
    "àcid píric": { numero: "660", estado: "líquid", tipo: "orgánico" },
    "àcid 1-octanosulfónic sal sòdica": { numero: "661", estado: "sòlid", tipo: "orgánico" },
    "l-cisteïna": { numero: "662", estado: "sòlid", tipo: "orgánico" },
    "n,n-dietil-1,4-fenilendiamonisulfat": { numero: "663", estado: "sòlid", tipo: "orgánico" },
    "parafina llenties": { numero: "664", estado: "sòlid", tipo: "orgánico" },
    "2-naftol": { numero: "665", estado: "sòlid", tipo: "orgánico" },
    "àcid làctic": { numero: "666", estado: "líquid", tipo: "orgánico" },
    "2-tert-butil-4-metoxifenol": { numero: "667", estado: "sòlid", tipo: "orgánico" },
    "2,4-di-tert-butil-4-metilfenol": { numero: "669", estado: "sòlid", tipo: "orgánico" },
    "àcid sulfàmic": { numero: "671", estado: "sòlid", tipo: "orgánico" },
    "n-ciclohexil sulfamat de sodi": { numero: "671c", estado: "sòlid", tipo: "orgánico" },
    "n-ciclohexil sulfàmic àcid": { numero: "671b", estado: "sòlid", tipo: "orgánico" },
    "l-fenilamina": { numero: "673", estado: "sòlid", tipo: "orgánico" },
    "cel.lulosa microcristal.lina": { numero: "674", estado: "sòlid", tipo: "orgánico" },
    "4,4-aminoantipirina": { numero: "676", estado: "sòlid", tipo: "orgánico" },
    "àcid fumàric": { numero: "678", estado: "sòlid", tipo: "orgánico" },
    "maltosa": { numero: "679", estado: "sòlid", tipo: "orgánico" },
    "estereat càlcic": { numero: "680", estado: "sòlid", tipo: "orgánico" },
    "nipagin": { numero: "681", estado: "sòlid", tipo: "orgánico" },
    "4-hidroxibenzoat d'etil": { numero: "682", estado: "sòlid", tipo: "orgánico" },
    "àcid tànnic": { numero: "683", estado: "sòlid", tipo: "orgánico" },
    "àcid 4-sulfobenzòic": { numero: "685", estado: "sòlid", tipo: "orgánico" },
    "toluolsulfonsaeureamida": { numero: "686", estado: "sòlid", tipo: "orgánico" },
    "acetobrom-a-d-glucosa": { numero: "687", estado: "líquid", tipo: "orgánico" },
    "8-hidroxiquinaldine": { numero: "688", estado: "sòlid", tipo: "orgánico" },
    "metil antranilate": { numero: "689", estado: "líquid", tipo: "orgánico" },
    "trifluoroacètic": { numero: "690", estado: "líquid", tipo: "orgánico" },
    "sacarina": { numero: "691", estado: "sòlid", tipo: "orgánico" },
    "àcid ciclàmic": { numero: "692", estado: "sòlid", tipo: "orgánico" },
    "2-tert-butil-4-metilfenol": { numero: "693", estado: "sòlid", tipo: "orgánico" },
    "acetaldehido": { numero: "694", estado: "líquid", tipo: "orgánico" },
    "limonene": { numero: "695", estado: "líquid", tipo: "orgánico" },
    "1-naftol escames": { numero: "698", estado: "sòlid", tipo: "orgánico" },
    "1-naftol pols": { numero: "698b", estado: "sòlid", tipo: "orgánico" },
    "glutamat sòdic": { numero: "699", estado: "sòlid", tipo: "orgánico" },
    "vaselina": { numero: "700", estado: "sòlid", tipo: "orgánico" },
    "polietilenglicol 1500": { numero: "701c", estado: "sòlid", tipo: "orgánico" },
    "polietilenglicol 2000": { numero: "701b", estado: "líquid", tipo: "orgánico" },
    "polietilenglicol 6000": { numero: "701", estado: "sòlid", tipo: "orgánico" },
    "maltotriosa": { numero: "702", estado: "sòlid", tipo: "orgánico" },
    "etil laurat, kosher": { numero: "703", estado: "líquid", tipo: "orgánico" },
    "sacarosa palmitat": { numero: "705", estado: "sòlid", tipo: "orgánico" },
    "àcid acètic": { numero: "716", estado: "líquid", tipo: "orgánico" },
    "2 aminofenol": { numero: "718b", estado: "sòlid", tipo: "orgánico" },
    "4-aminofenol": { numero: "718", estado: "sòlid", tipo: "orgánico" },
    "4 acetamidofenol": { numero: "723", estado: "sòlid", tipo: "orgánico" },
    "ftalat de dietil": { numero: "728", estado: "líquid", tipo: "orgánico" },
    "àcid valèric": { numero: "729", estado: "líquid", tipo: "orgánico" },
    "o-tolidina 0,1 sol": { numero: "730", estado: "líquid", tipo: "orgánico" },
    "o-tolidina pur": { numero: "730b", estado: "sòlid", tipo: "orgánico" },
    "àcid 3 metilsalicilic": { numero: "731", estado: "sòlid", tipo: "orgánico" },
    "citral": { numero: "732", estado: "líquid", tipo: "orgánico" },
    "anisole": { numero: "733", estado: "líquid", tipo: "orgánico" },
    "sucralose": { numero: "734", estado: "sòlid", tipo: "orgánico" },
    "n-n-dimetilacetamida": { numero: "736", estado: "líquid", tipo: "orgánico" },
    "acid galacturonic * h2o": { numero: "737", estado: "sòlid", tipo: "orgánico" },
    "p-cresol": { numero: "738", estado: "líquid", tipo: "orgánico" },
    "carbazol": { numero: "739", estado: "sòlid", tipo: "orgánico" },
    "antrona": { numero: "740", estado: "sòlid", tipo: "orgánico" },
    "5-hidroximetil-2-furaldehid": { numero: "741", estado: "líquid", tipo: "orgánico" },
    "4-etilfenol": { numero: "742", estado: "sòlid", tipo: "orgánico" },
    "o-toluidina": { numero: "541b", estado: "sòlid", tipo: "orgánico" },
    "amina": { numero: "743", estado: "líquid", tipo: "orgánico" },
    "dipohenilamine": { numero: "744", estado: "sòlid", tipo: "orgánico" },
    "citrato de sodio dihidratado": { numero: "745", estado: "sòlid", tipo: "orgánico" },
    "àcid tricloroacètic": { numero: "746", estado: "sòlid", tipo: "orgánico" },

    // Reactivos inorgánicos
    "acetat d'amoni": { numero: "10", estado: "sòlid", tipo: "inorgánico" },
    "acetat de bari": { numero: "25", estado: "sòlid", tipo: "inorgánico" },
    "acetat de calci. xh2o": { numero: "22", estado: "sòlid", tipo: "inorgánico" },
    "acetat de calci.1h2o": { numero: "22b", estado: "sòlid", tipo: "inorgánico" },
    "acetat de coure (ii)": { numero: "207", estado: "sòlid", tipo: "inorgánico" },
    "acetat de coure (ii) 1h2o": { numero: "207b", estado: "sòlid", tipo: "inorgánico" },
    "acetat de magnesi": { numero: "203", estado: "sòlid", tipo: "inorgánico" },
    "acetat de magnesi 4h2o": { numero: "203b", estado: "sòlid", tipo: "inorgánico" },
    "acetat de mercuri (ii)": { numero: "209", estado: "sòlid", tipo: "inorgánico" },
    "acetat de niquel (ii)": { numero: "245", estado: "sòlid", tipo: "inorgánico" },
    "acetat de niquel (ii) 4h2o": { numero: "245b", estado: "sòlid", tipo: "inorgánico" },
    "acetat de potasi": { numero: "8", estado: "sòlid", tipo: "inorgánico" },
    "acetat de sodi": { numero: "120", estado: "sòlid", tipo: "inorgánico" },
    "acetat de sodi 3h2o": { numero: "120b", estado: "sòlid", tipo: "inorgánico" },
    "acetat de zinc": { numero: "2", estado: "sòlid", tipo: "inorgánico" },
    "acetat de zinc 2h2o": { numero: "2b", estado: "sòlid", tipo: "inorgánico" },
    "acetat plom (ii)": { numero: "78", estado: "sòlid", tipo: "inorgánico" },
    "acetat plom (ii) 3h2o": { numero: "78b", estado: "sòlid", tipo: "inorgánico" },
    "àcid bòric": { numero: "1", estado: "sòlid", tipo: "inorgánico" },
    "àcid fosfomolíbdic x h2o": { numero: "197", estado: "sòlid", tipo: "inorgánico" },
    "àcid ortofosfòric": { numero: "182", estado: "líquid", tipo: "inorgánico" },
    "aigua per cromatografia": { numero: "257", estado: "líquid", tipo: "inorgánico" },
    "al·liatge de de varda": { numero: "155", estado: "sòlid", tipo: "inorgánico" },
    "alumini granalla": { numero: "6", estado: "sòlid", tipo: "inorgánico" },
    "alumini metall pols": { numero: "6b", estado: "sòlid", tipo: "inorgánico" },
    "amoni monovanadat": { numero: "76", estado: "sòlid", tipo: "inorgánico" },
    "arsenit de sodi": { numero: "121", estado: "sòlid", tipo: "inorgánico" },
    "azida de sodi": { numero: "205", estado: "sòlid", tipo: "inorgánico" },
    "benzoat de sodi": { numero: "211", estado: "sòlid", tipo: "inorgánico" },
    "bismutat de sodi": { numero: "169", estado: "sòlid", tipo: "inorgánico" },
    "bitartrat de potasi": { numero: "85", estado: "sòlid", tipo: "inorgánico" },
    "borohidrur de sodi": { numero: "216", estado: "sòlid", tipo: "inorgánico" },
    "bromat de potasi": { numero: "44", estado: "sòlid", tipo: "inorgánico" },
    "bromur de potasi": { numero: "86", estado: "sòlid", tipo: "inorgánico" },
    "bromur de potasi 0,1m (fixanal)": { numero: "86b", estado: "líquid", tipo: "inorgánico" },
    "bromur de sodi": { numero: "166", estado: "sòlid", tipo: "inorgánico" },
    "cadmi metall granalla": { numero: "226", estado: "sòlid", tipo: "inorgánico" },
    "cal baritada": { numero: "38", estado: "sòlid", tipo: "inorgánico" },
    "cal sodada en lentejas": { numero: "39b", estado: "sòlid", tipo: "inorgánico" },
    "cal sodada gránulos": { numero: "39", estado: "sòlid", tipo: "inorgánico" },
    "calci hidrogen fosfat": { numero: "251", estado: "sòlid", tipo: "inorgánico" },
    "calci hidrogen fosfat 2h2o": { numero: "251b", estado: "sòlid", tipo: "inorgánico" },
    "carbó actiu granulat": { numero: "40b", estado: "sòlid", tipo: "inorgánico" },
    "carbó actiu pols": { numero: "40", estado: "sòlid", tipo: "inorgánico" },
    "carbonat amoni": { numero: "179", estado: "sòlid", tipo: "inorgánico" },
    "carbonat de bari": { numero: "221", estado: "sòlid", tipo: "inorgánico" },
    "carbonat de calci": { numero: "32", estado: "sòlid", tipo: "inorgánico" },
    "carbonat de liti": { numero: "164", estado: "sòlid", tipo: "inorgánico" },
    "carbonat de magnesi": { numero: "61", estado: "sòlid", tipo: "inorgánico" },
    "carbonat de plom (ii)": { numero: "15", estado: "sòlid", tipo: "inorgánico" },
    "carbonat de potasi": { numero: "162", estado: "sòlid", tipo: "inorgánico" },
    "carbonat de sodi": { numero: "123", estado: "sòlid", tipo: "inorgánico" },
    "carbonat de sodi 2h2o": { numero: "123b", estado: "sòlid", tipo: "inorgánico" },
    "carbonat de zinc": { numero: "222", estado: "sòlid", tipo: "inorgánico" },
    "cianur de potasi": { numero: "238", estado: "sòlid", tipo: "inorgánico" },
    "cinta magnesi": { numero: "174", estado: "sòlid", tipo: "inorgánico" },
    "citrat d'amoni i ferro (iii)": { numero: "191", estado: "sòlid", tipo: "inorgánico" },
    "citrat de ferro (iii)": { numero: "195", estado: "sòlid", tipo: "inorgánico" },
    "citrat de ferro (iii) 1h2o": { numero: "195b", estado: "sòlid", tipo: "inorgánico" },
    "citrat de magnesi": { numero: "249", estado: "sòlid", tipo: "inorgánico" },
    "citrat potàssic": { numero: "234", estado: "sòlid", tipo: "inorgánico" },
    "citrat potàssic 1h2o": { numero: "234b", estado: "sòlid", tipo: "inorgánico" },
    "citrat trisodi": { numero: "125", estado: "sòlid", tipo: "inorgánico" },
    "citrat trisodi 2h2o": { numero: "125b", estado: "sòlid", tipo: "inorgánico" },
    "clorat de potasi": { numero: "88", estado: "sòlid", tipo: "inorgánico" },
    "clorat de sodi": { numero: "263", estado: "sòlid", tipo: "inorgánico" },
    "clorur cobalt(ii)": { numero: "42", estado: "sòlid", tipo: "inorgánico" },
    "clorur cobalt(ii) 6h2o": { numero: "42b", estado: "sòlid", tipo: "inorgánico" },
    "clorur d'alumini": { numero: "178", estado: "sòlid", tipo: "inorgánico" },
    "clorur d'alumini 6h2o": { numero: "178b", estado: "sòlid", tipo: "inorgánico" },
    "clorur d'amoni": { numero: "12", estado: "sòlid", tipo: "inorgánico" },
    "clorur d'estany (iv) 5h2o": { numero: "269b", estado: "sòlid", tipo: "inorgánico" },
    "clorur de bari": { numero: "161", estado: "sòlid", tipo: "inorgánico" },
    "clorur de bari 1h2o": { numero: "161b", estado: "sòlid", tipo: "inorgánico" },
    "clorur de bari 2h2o": { numero: "161c", estado: "sòlid", tipo: "inorgánico" },
    "clorur de bismut (iii)": { numero: "258", estado: "sòlid", tipo: "inorgánico" },
    "clorur de calci 2h2o": { numero: "34b", estado: "sòlid", tipo: "inorgánico" },
    "clorur de calci 6h2o": { numero: "34c", estado: "sòlid", tipo: "inorgánico" },
    "clorur de calci granulat": { numero: "34", estado: "sòlid", tipo: "inorgánico" },
    "clorur de cesi (iii)": { numero: "50", estado: "sòlid", tipo: "inorgánico" },
    "clorur de coure (ii)": { numero: "45", estado: "sòlid", tipo: "inorgánico" },
    "clorur de ferro (ii)": { numero: "115", estado: "sòlid", tipo: "inorgánico" },
    "clorur de ferro (ii) 4h2o": { numero: "115b", estado: "sòlid", tipo: "inorgánico" },
    "clorur de liti": { numero: "170", estado: "sòlid", tipo: "inorgánico" },
    "clorur de magnesi 6h2o": { numero: "55b", estado: "sòlid", tipo: "inorgánico" },
    "clorur de magnesi xh2o": { numero: "55", estado: "sòlid", tipo: "inorgánico" },
    "clorur de manganès (ii)": { numero: "66", estado: "sòlid", tipo: "inorgánico" },
    "clorur de manganès (ii) 4h2o": { numero: "66b", estado: "sòlid", tipo: "inorgánico" },
    "clorur de mercuri (ii)": { numero: "167", estado: "sòlid", tipo: "inorgánico" },
    "clorur de níquel(ii)": { numero: "225", estado: "sòlid", tipo: "inorgánico" },
    "clorur de níquel(ii) 6h2o": { numero: "225b", estado: "sòlid", tipo: "inorgánico" },
    "clorur de paladi": { numero: "190", estado: "sòlid", tipo: "inorgánico" },
    "clorur de potasi": { numero: "89", estado: "sòlid", tipo: "inorgánico" },
    "clorur de sodi": { numero: "5", estado: "sòlid", tipo: "inorgánico" },
    "clorur de titani (iii)": { numero: "219", estado: "sòlid", tipo: "inorgánico" },
    "clorur de zinc": { numero: "159", estado: "sòlid", tipo: "inorgánico" },
    "clorur de zinc 2h2o": { numero: "159b", estado: "sòlid", tipo: "inorgánico" },
    "clorur estany (ii)": { numero: "51", estado: "sòlid", tipo: "inorgánico" },
    "clorur estany (ii) 2h2o": { numero: "51b", estado: "sòlid", tipo: "inorgánico" },
    "clorur estronci": { numero: "217", estado: "sòlid", tipo: "inorgánico" },
    "clorur estronci 6h2o": { numero: "217b", estado: "sòlid", tipo: "inorgánico" },
    "clorur ferro(iii)": { numero: "58", estado: "sòlid", tipo: "inorgánico" },
    "clorur ferro(iii) 6h2o": { numero: "58b", estado: "sòlid", tipo: "inorgánico" },
    "coure (i) bromur": { numero: "134", estado: "sòlid", tipo: "inorgánico" },
    "coure metàlic pols": { numero: "46", estado: "sòlid", tipo: "inorgánico" },
    "cromat de bari": { numero: "224", estado: "sòlid", tipo: "inorgánico" },
    "cromat de coure (ii)": { numero: "236", estado: "sòlid", tipo: "inorgánico" },
    "cromat de coure (ii) 2h2o": { numero: "236b", estado: "sòlid", tipo: "inorgánico" },
    "cromat de potasi": { numero: "90", estado: "sòlid", tipo: "inorgánico" },
    "cromat de sodi": { numero: "201", estado: "sòlid", tipo: "inorgánico" },
    "dicromat de potasi": { numero: "91", estado: "sòlid", tipo: "inorgánico" },
    "dicromat de sodi": { numero: "75", estado: "sòlid", tipo: "inorgánico" },
    "dicromat de sodi 2 h2o": { numero: "75b", estado: "sòlid", tipo: "inorgánico" },
    "dietilditiocarbamat de plata": { numero: "213", estado: "sòlid", tipo: "inorgánico" },
    "dihidrògenfosfat amoni": { numero: "173", estado: "sòlid", tipo: "inorgánico" },
    "dihidrògenfosfat de potasi": { numero: "97", estado: "sòlid", tipo: "inorgánico" },
    "dihidrogenfosfat de sodi": { numero: "135", estado: "sòlid", tipo: "inorgánico" },
    "dihidrogenfosfat de sodi 1 h2o": { numero: "135b", estado: "sòlid", tipo: "inorgánico" },
    "dihidrogenfosfat de sodi 2 h2o": { numero: "135c", estado: "sòlid", tipo: "inorgánico" },
    "diòxid de manganès": { numero: "65", estado: "sòlid", tipo: "inorgánico" },
    "disulfit de potasi": { numero: "98", estado: "sòlid", tipo: "inorgánico" },
    "disulfit de sodi": { numero: "127", estado: "sòlid", tipo: "inorgánico" },
    "disulfur de carboni": { numero: "266", estado: "líquid", tipo: "inorgánico" },
    "ditiocarbamat de sodi": { numero: "188", estado: "sòlid", tipo: "inorgánico" },
    "ditiocarbamat de sodi 3h2o": { numero: "188b", estado: "sòlid", tipo: "inorgánico" },
    "edta, sal disòdica": { numero: "3", estado: "sòlid", tipo: "inorgánico" },
    "edta, sal disòdica 2h2o": { numero: "3b", estado: "sòlid", tipo: "inorgánico" },
    "estany granalla": { numero: "163b", estado: "sòlid", tipo: "inorgánico" },
    "estany granulat": { numero: "163", estado: "sòlid", tipo: "inorgánico" },
    "estany pols": { numero: "163c", estado: "sòlid", tipo: "inorgánico" },
    "ferro metàlic pols": { numero: "57", estado: "sòlid", tipo: "inorgánico" },
    "fil de coure": { numero: "175", estado: "sòlid", tipo: "inorgánico" },
    "fluorur de potasi": { numero: "53", estado: "sòlid", tipo: "inorgánico" },
    "fluorur de sodi": { numero: "128", estado: "sòlid", tipo: "inorgánico" },
    "formiat d'amoni": { numero: "158", estado: "sòlid", tipo: "inorgánico" },
    "formiat de sodi": { numero: "231", estado: "sòlid", tipo: "inorgánico" },
    "fosfat de calci": { numero: "204", estado: "sòlid", tipo: "inorgánico" },
    "fosfat de potasi": { numero: "94", estado: "sòlid", tipo: "inorgánico" },
    "fosfat de potasi 3 h20": { numero: "94b", estado: "sòlid", tipo: "inorgánico" },
    "fosfat de sodi": { numero: "145", estado: "sòlid", tipo: "inorgánico" },
    "fosfat de sodi *12 h2o": { numero: "145b", estado: "sòlid", tipo: "inorgánico" },
    "hexacianoferrat (ii) de potassi": { numero: "95", estado: "sòlid", tipo: "inorgánico" },
    "hexacianoferrat (ii) de potassi 3h2o": { numero: "95b", estado: "sòlid", tipo: "inorgánico" },
    "hexacianoferrat (iii) de potassi": { numero: "92", estado: "sòlid", tipo: "inorgánico" },
    "hexacloroplatinat(iv) potasi": { numero: "172", estado: "sòlid", tipo: "inorgánico" },
    "hexadrixoantimoniat(v) potasi": { numero: "210", estado: "sòlid", tipo: "inorgánico" },
    "hidrògen citrat d'amoni": { numero: "150", estado: "sòlid", tipo: "inorgánico" },
    "hidrogen fosfat d'amoni": { numero: "14", estado: "sòlid", tipo: "inorgánico" },
    "hidrògen ftalat potasi": { numero: "83", estado: "sòlid", tipo: "inorgánico" },
    "hidrogencarbonat de potasi": { numero: "82", estado: "sòlid", tipo: "inorgánico" },
    "hidrogencarbonat de sodi": { numero: "124", estado: "sòlid", tipo: "inorgánico" },
    "hidrògenfosfat de potasi": { numero: "100", estado: "sòlid", tipo: "inorgánico" },
    "hidrogenoxalat de potasi": { numero: "87", estado: "sòlid", tipo: "inorgánico" },
    "hidrògensulfat de potasi": { numero: "30", estado: "sòlid", tipo: "inorgánico" },
    "hidrogensulfit de sodi": { numero: "122", estado: "sòlid", tipo: "inorgánico" },
    "hidrogensulfit de sodi 40%": { numero: "122c", estado: "líquid", tipo: "inorgánico" },
    "hidrogensulfit de sodi x h2o": { numero: "122b", estado: "sòlid", tipo: "inorgánico" },
    "hidrogentartrat de sodi": { numero: "184", estado: "sòlid", tipo: "inorgánico" },
    "hidrosulfit de sodi": { numero: "250", estado: "sòlid", tipo: "inorgánico" },
    "hidroxiacetat plom (ii)": { numero: "168", estado: "sòlid", tipo: "inorgánico" },
    "hidròxid carbonat magnesi": { numero: "206", estado: "sòlid", tipo: "inorgánico" },
    "hidròxid carbonat magnesi 5 h2o": { numero: "206b", estado: "sòlid", tipo: "inorgánico" },
    "hidròxid d'alumini": { numero: "262", estado: "sòlid", tipo: "inorgánico" },
    "hidròxid de bari": { numero: "26", estado: "sòlid", tipo: "inorgánico" },
    "hidròxid de bari 8 h2o": { numero: "26b", estado: "sòlid", tipo: "inorgánico" },
    "hidròxid de calci": { numero: "35", estado: "sòlid", tipo: "inorgánico" },
    "hidròxid de liti": { numero: "194", estado: "sòlid", tipo: "inorgánico" },
    "hidròxid de liti 1h2o": { numero: "194b", estado: "sòlid", tipo: "inorgánico" },
    "hidròxid de potasi": { numero: "114", estado: "sòlid", tipo: "inorgánico" },
    "hidròxid de sodi": { numero: "130", estado: "sòlid", tipo: "inorgánico" },
    "hidròxid de zinc": { numero: "230", estado: "sòlid", tipo: "inorgánico" },
    "hidròxid magnesi": { numero: "62", estado: "sòlid", tipo: "inorgánico" },
    "hipoclorit de sodi": { numero: "193", estado: "líquid", tipo: "inorgánico" },
    "iodat de potasi": { numero: "96", estado: "sòlid", tipo: "inorgánico" },
    "iodat de sodi": { numero: "239", estado: "sòlid", tipo: "inorgánico" },
    "iode": { numero: "154", estado: "sòlid", tipo: "inorgánico" },
    "iodur de mercuri (ii)": { numero: "28", estado: "sòlid", tipo: "inorgánico" },
    "iodur de potasi": { numero: "110", estado: "sòlid", tipo: "inorgánico" },
    "iodur de sodi": { numero: "214", estado: "sòlid", tipo: "inorgánico" },
    "llana de vidre": { numero: "254", estado: "sòlid", tipo: "inorgánico" },
    "magnesi l-lactat x hidratat": { numero: "253", estado: "sòlid", tipo: "inorgánico" },
    "magnesi pols": { numero: "68", estado: "sòlid", tipo: "inorgánico" },
    "metavanadat d'amoni": { numero: "21", estado: "sòlid", tipo: "inorgánico" },
    "molibdat d'amoni": { numero: "131", estado: "sòlid", tipo: "inorgánico" },
    "molibdat d'amoni 4 h2o": { numero: "131b", estado: "sòlid", tipo: "inorgánico" },
    "molibdat de sodi": { numero: "140", estado: "sòlid", tipo: "inorgánico" },
    "molibdat de sodi 2 h2o": { numero: "140b", estado: "sòlid", tipo: "inorgánico" },
    "molibdat potàsic": { numero: "187", estado: "sòlid", tipo: "inorgánico" },
    "n metafosfat de sodi": { numero: "136b", estado: "sòlid", tipo: "inorgánico" },
    "níquel pols": { numero: "218", estado: "sòlid", tipo: "inorgánico" },
    "nitrats d'alumini": { numero: "261", estado: "sòlid", tipo: "inorgánico" },
    "nitrats d'alumini 9h2o": { numero: "261b", estado: "sòlid", tipo: "inorgánico" },
    "nitrats d'amoni": { numero: "16", estado: "sòlid", tipo: "inorgánico" },
    "nitrats d'estronci": { numero: "165", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de bari": { numero: "27", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de bismut": { numero: "4", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de cadmi": { numero: "31", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de calci": { numero: "177", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de calci 4h2o": { numero: "177b", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de cobalt (ii)": { numero: "43", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de coure(ii)": { numero: "111", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de coure(ii) 3h2o": { numero: "111b", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de crom (iii)": { numero: "72", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de crom (iii) 9h2o": { numero: "72b", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de ferro (iii)": { numero: "60", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de ferro (iii) 9h2o": { numero: "60b", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de lantà (iii)": { numero: "11", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de lantà (iii). 6h2o": { numero: "11b", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de liti": { numero: "106", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de magnesi": { numero: "63", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de magnesi 6 h2o": { numero: "63b", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de mercuri (i)": { numero: "199", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de mercuri (i) 2h2o": { numero: "199b", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de mercuri (i) h2o": { numero: "199c", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de mercuri (ii)": { numero: "70", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de plata": { numero: "171", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de plom (ii)": { numero: "180", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de potasi": { numero: "101", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de sodi": { numero: "133", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de zinc": { numero: "160", estado: "sòlid", tipo: "inorgánico" },
    "nitrats de zinc 6 h2o": { numero: "160b", estado: "sòlid", tipo: "inorgánico" },
    "nitrit de sodi": { numero: "137", estado: "sòlid", tipo: "inorgánico" },
    "nitrit potasi": { numero: "200", estado: "sòlid", tipo: "inorgánico" },
    "oxalat d'amoni i ferro (iii)": { numero: "243", estado: "sòlid", tipo: "inorgánico" },
    "oxalat d'amoni i ferro (iii) 3h2o": { numero: "243b", estado: "sòlid", tipo: "inorgánico" },
    "oxalat de bari": { numero: "267", estado: "sòlid", tipo: "inorgánico" },
    "oxalat de d'amoni": { numero: "18", estado: "sòlid", tipo: "inorgánico" },
    "oxalat de d'amoni 1h2o": { numero: "18b", estado: "sòlid", tipo: "inorgánico" },
    "oxalat de potasi": { numero: "198", estado: "sòlid", tipo: "inorgánico" },
    "oxalat de potasi 1 h2o": { numero: "198b", estado: "sòlid", tipo: "inorgánico" },
    "oxalat de sodi": { numero: "138", estado: "sòlid", tipo: "inorgánico" },
    "òxid d'alumini": { numero: "7", estado: "sòlid", tipo: "inorgánico" },
    "òxid d'arsènic(iii)": { numero: "23", estado: "sòlid", tipo: "inorgánico" },
    "òxid de calci": { numero: "36", estado: "sòlid", tipo: "inorgánico" },
    "òxid de coure (ii)": { numero: "48", estado: "sòlid", tipo: "inorgánico" },
    "òxid de crom (vi)": { numero: "77", estado: "sòlid", tipo: "inorgánico" },
    "òxid de lantà": { numero: "73", estado: "sòlid", tipo: "inorgánico" },
    "òxid de magnesi": { numero: "64", estado: "sòlid", tipo: "inorgánico" },
    "òxid de mercuri (ii)": { numero: "69", estado: "sòlid", tipo: "inorgánico" },
    "òxid de plom (ii)": { numero: "81", estado: "sòlid", tipo: "inorgánico" },
    "òxid de vanadi (v)": { numero: "196", estado: "sòlid", tipo: "inorgánico" },
    "òxid de zinc": { numero: "229", estado: "sòlid", tipo: "inorgánico" },
    "òxid manganòs (ii)": { numero: "259", estado: "sòlid", tipo: "inorgánico" },
    "perborat de sodi": { numero: "246", estado: "sòlid", tipo: "inorgánico" },
    "perborat de sodi 4 h2o": { numero: "246b", estado: "sòlid", tipo: "inorgánico" },
    "perclorat de bari": { numero: "176", estado: "sòlid", tipo: "inorgánico" },
    "perclorat de potasi": { numero: "102", estado: "sòlid", tipo: "inorgánico" },
    "periodat de potasi": { numero: "99", estado: "sòlid", tipo: "inorgánico" },
    "permanganat de potasi": { numero: "103", estado: "sòlid", tipo: "inorgánico" },
    "peròxid de sodi": { numero: "139", estado: "sòlid", tipo: "inorgánico" },
    "peroxodisulfat d'amoni": { numero: "19", estado: "sòlid", tipo: "inorgánico" },
    "peroxodisulfat de potasi": { numero: "116", estado: "sòlid", tipo: "inorgánico" },
    "plom (iv) òxid": { numero: "113", estado: "sòlid", tipo: "inorgánico" },
    "plom metàlic granalla": { numero: "79b", estado: "sòlid", tipo: "inorgánico" },
    "plom metàlic laminas": { numero: "79", estado: "sòlid", tipo: "inorgánico" },
    "policlorur d'alumini": { numero: "181", estado: "sòlid", tipo: "inorgánico" },
    "potasi hidrogenfosfat-12h2o": { numero: "100b", estado: "sòlid", tipo: "inorgánico" },
    "sal·licilat de sodi": { numero: "112", estado: "sòlid", tipo: "inorgánico" },
    "silica gel": { numero: "118", estado: "sòlid", tipo: "inorgánico" },
    "silicona líquida": { numero: "117", estado: "líquid", tipo: "inorgánico" },
    "sodi aluminat anhidre": { numero: "256", estado: "sòlid", tipo: "inorgánico" },
    "sodi hexametafosfat": { numero: "136", estado: "sòlid", tipo: "inorgánico" },
    "sodi hidrogenfosfat": { numero: "129", estado: "sòlid", tipo: "inorgánico" },
    "sodi hidrogenfosfat 12h2o": { numero: "129c", estado: "sòlid", tipo: "inorgánico" },
    "sodi metal, barras": { numero: "119", estado: "sòlid", tipo: "inorgánico" },
    "sodi pentacianonitrosferrat(iii)": { numero: "84", estado: "sòlid", tipo: "inorgánico" },
    "sodi pentacianonitrosferrat(iii) 2h2o": { numero: "84b", estado: "sòlid", tipo: "inorgánico" },
    "sodi pirofosfat": { numero: "104", estado: "sòlid", tipo: "inorgánico" },
    "sodi tetra-fenilborat": { numero: "153", estado: "sòlid", tipo: "inorgánico" },
    "sodi, hidrogen fosfat 2.h2o": { numero: "129b", estado: "sòlid", tipo: "inorgánico" },
    "sofre sublimat": { numero: "24", estado: "sòlid", tipo: "inorgánico" },
    "sorbat de potasi": { numero: "212", estado: "sòlid", tipo: "inorgánico" },
    "succinat de sodi": { numero: "183", estado: "sòlid", tipo: "inorgánico" },
    "succinat de sodi 6 h2o": { numero: "183b", estado: "sòlid", tipo: "inorgánico" },
    "sulfat alumini 18 h2o": { numero: "9b", estado: "sòlid", tipo: "inorgánico" },
    "sulfat alumini i amoni": { numero: "208", estado: "sòlid", tipo: "inorgánico" },
    "sulfat alumini i amoni 12 h2o": { numero: "208b", estado: "sòlid", tipo: "inorgánico" },
    "sulfat aluminic potasic": { numero: "105", estado: "sòlid", tipo: "inorgánico" },
    "sulfat aluminic potasic 12h2o": { numero: "105b", estado: "sòlid", tipo: "inorgánico" },
    "sulfat d'alumini (granulat)": { numero: "9", estado: "sòlid", tipo: "inorgánico" },
    "sulfat d'amoni": { numero: "20", estado: "sòlid", tipo: "inorgánico" },
    "sulfat d'estronci": { numero: "235", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de bari": { numero: "223", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de cadmi": { numero: "264", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de calci": { numero: "37", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de calci 2 h2o": { numero: "37b", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de ceri": { numero: "41", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de coure (ii)": { numero: "47", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de coure (ii) 5h2o": { numero: "47b", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de crom (iii) i potasi": { numero: "252", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de ferro (ii) 7 h2o": { numero: "59b", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de ferro(ii)": { numero: "59", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de ferro(ii) i amoni": { numero: "13", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de ferro(ii) i amoni 6h2o": { numero: "13b", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de ferro(iii) i amoni": { numero: "186", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de ferro(iii) i amoni * 12 h2o": { numero: "186b", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de ferro(iii).": { numero: "192", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de ferro(iii). x h2o": { numero: "192b", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de liti": { numero: "265", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de magnesi": { numero: "17", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de magnesi 7 h2o": { numero: "17b", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de manganès (ii)": { numero: "67", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de manganès (ii) 1h2o": { numero: "67b", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de mercuri (ii)": { numero: "71", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de níquel (ii)": { numero: "74", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de níquel (ii) 6h2o": { numero: "74b", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de níquel(ii) i amoni": { numero: "241", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de níquel(ii) i amoni 6h2o": { numero: "241b", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de plata": { numero: "152", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de potasi": { numero: "107", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de sodi": { numero: "141", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de sodi 10 h2o": { numero: "141b", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de sodi dodecilo": { numero: "126", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de zinc": { numero: "49", estado: "sòlid", tipo: "inorgánico" },
    "sulfat de zinc 7 h2o": { numero: "49b", estado: "sòlid", tipo: "inorgánico" },
    "sulfit de sodi": { numero: "142", estado: "sòlid", tipo: "inorgánico" },
    "sulfocianur amònic": { numero: "233", estado: "sòlid", tipo: "inorgánico" },
    "sulfur de ferro (ii)": { numero: "56", estado: "sòlid", tipo: "inorgánico" },
    "sulfur de potasi": { numero: "240", estado: "sòlid", tipo: "inorgánico" },
    "sulfur de sodi 3 h2o": { numero: "147b", estado: "sòlid", tipo: "inorgánico" },
    "sulfur de sodi x h2o": { numero: "147", estado: "sòlid", tipo: "inorgánico" },
    "talc": { numero: "29", estado: "sòlid", tipo: "inorgánico" },
    "tartrat d'antimoni(iii) i potasi": { numero: "202", estado: "sòlid", tipo: "inorgánico" },
    "tartrat d'antimoni(iii) i potasi 0,5 h2o": { numero: "202b", estado: "sòlid", tipo: "inorgánico" },
    "tartrat de sodi": { numero: "54", estado: "sòlid", tipo: "inorgánico" },
    "tartrat de sodi 2h2o": { numero: "54b", estado: "sòlid", tipo: "inorgánico" },
    "tartrat de sodi i potasi": { numero: "109", estado: "sòlid", tipo: "inorgánico" },
    "tartrat de sodi i potasi 4 h2o": { numero: "109b", estado: "sòlid", tipo: "inorgánico" },
    "tartrat doble potasi i antimoni (iii)": { numero: "132", estado: "sòlid", tipo: "inorgánico" },
    "tartrat doble potasi i antimoni (iii) 1/2h2o": { numero: "132c", estado: "sòlid", tipo: "inorgánico" },
    "tartrat doble potasi i antimoni (iii) 3 h2o": { numero: "132b", estado: "sòlid", tipo: "inorgánico" },
    "tetraborat disodi.10 h2o": { numero: "143b", estado: "sòlid", tipo: "inorgánico" },
    "tetraborat sodi": { numero: "143", estado: "sòlid", tipo: "inorgánico" },
    "tetraòxid plom": { numero: "80", estado: "sòlid", tipo: "inorgánico" },
    "tiocianat d'amoni": { numero: "237", estado: "sòlid", tipo: "inorgánico" },
    "tiocianat de potasi": { numero: "108", estado: "sòlid", tipo: "inorgánico" },
    "tiosulfat de sodi": { numero: "148", estado: "sòlid", tipo: "inorgánico" },
    "tiosulfat de sodi.5 h2o": { numero: "148b", estado: "sòlid", tipo: "inorgánico" },
    "wolframat de sodi": { numero: "149", estado: "sòlid", tipo: "inorgánico" },
    "zinc en varillas": { numero: "156b", estado: "sòlid", tipo: "inorgánico" },
    "zinc metall granulat": { numero: "156", estado: "sòlid", tipo: "inorgánico" },
    "zinc pols": { numero: "156c", estado: "sòlid", tipo: "inorgánico" },
    "clorur d'estany (iv)": { numero: "269", estado: "sòlid", tipo: "inorgánico" },
    "benzoat de potassi": { numero: "270", estado: "sòlid", tipo: "inorgánico" },
    "hidroxid amònic per hplc": { numero: "272", estado: "líquid", tipo: "inorgánico" },
    "oxalat de di-potassi": { numero: "273", estado: "sòlid", tipo: "inorgánico" },
    "àcid tricloroacètic": { numero: "274", estado: "sòlid", tipo: "inorgánico" },
};

// Función para buscar un reactivo por nombre
function buscarReactivo() {
    const inputBusqueda = document.getElementById("nombreInput").value.trim().toLowerCase();
    const resultado = reactivos[inputBusqueda];

    const elementoResultado = document.getElementById("resultado");
    if (resultado) {
        elementoResultado.textContent = `Reactivo encontrado: Número ${resultado.numero}, Estado ${resultado.estado}, Tipo ${resultado.tipo}`;
    } else {
        elementoResultado.textContent = "Reactivo no encontrado.";
    }
}

// Función para mostrar todos los reactivos en la lista
function mostrarReactivos() {
    const listaReactivos = document.getElementById("listaReactivos");
    listaReactivos.innerHTML = "";

    for (const [nombre, datos] of Object.entries(reactivos)) {
        const li = document.createElement("li");
        li.textContent = `${nombre} - Número: ${datos.numero}, Estado: ${datos.estado}, Tipo: ${datos.tipo}`;
        listaReactivos.appendChild(li);
    }
}

// Mostrar los reactivos al cargar la página
mostrarReactivos();